/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libeps;

public class barra {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected barra(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(barra obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libepsJNI.delete_barra(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInd(int value) {
    libepsJNI.barra_ind_set(swigCPtr, this, value);
  }

  public int getInd() {
    return libepsJNI.barra_ind_get(swigCPtr, this);
  }

  public void setNome(String value) {
    libepsJNI.barra_nome_set(swigCPtr, this, value);
  }

  public String getNome() {
    return libepsJNI.barra_nome_get(swigCPtr, this);
  }

  public void setArea(int value) {
    libepsJNI.barra_area_set(swigCPtr, this, value);
  }

  public int getArea() {
    return libepsJNI.barra_area_get(swigCPtr, this);
  }

  public void setZonaPerdas(int value) {
    libepsJNI.barra_zonaPerdas_set(swigCPtr, this, value);
  }

  public int getZonaPerdas() {
    return libepsJNI.barra_zonaPerdas_get(swigCPtr, this);
  }

  public void setTipo(int value) {
    libepsJNI.barra_tipo_set(swigCPtr, this, value);
  }

  public int getTipo() {
    return libepsJNI.barra_tipo_get(swigCPtr, this);
  }

  public void setVEsp(double value) {
    libepsJNI.barra_vEsp_set(swigCPtr, this, value);
  }

  public double getVEsp() {
    return libepsJNI.barra_vEsp_get(swigCPtr, this);
  }

  public void setV(double value) {
    libepsJNI.barra_v_set(swigCPtr, this, value);
  }

  public double getV() {
    return libepsJNI.barra_v_get(swigCPtr, this);
  }

  public void setTheta(double value) {
    libepsJNI.barra_theta_set(swigCPtr, this, value);
  }

  public double getTheta() {
    return libepsJNI.barra_theta_get(swigCPtr, this);
  }

  public void setPc(double value) {
    libepsJNI.barra_pc_set(swigCPtr, this, value);
  }

  public double getPc() {
    return libepsJNI.barra_pc_get(swigCPtr, this);
  }

  public void setQc(double value) {
    libepsJNI.barra_qc_set(swigCPtr, this, value);
  }

  public double getQc() {
    return libepsJNI.barra_qc_get(swigCPtr, this);
  }

  public void setPg(double value) {
    libepsJNI.barra_pg_set(swigCPtr, this, value);
  }

  public double getPg() {
    return libepsJNI.barra_pg_get(swigCPtr, this);
  }

  public void setQg(double value) {
    libepsJNI.barra_qg_set(swigCPtr, this, value);
  }

  public double getQg() {
    return libepsJNI.barra_qg_get(swigCPtr, this);
  }

  public void setBaseKV(double value) {
    libepsJNI.barra_baseKV_set(swigCPtr, this, value);
  }

  public double getBaseKV() {
    return libepsJNI.barra_baseKV_get(swigCPtr, this);
  }

  public void setVgO(double value) {
    libepsJNI.barra_vgO_set(swigCPtr, this, value);
  }

  public double getVgO() {
    return libepsJNI.barra_vgO_get(swigCPtr, this);
  }

  public void setQgMax(double value) {
    libepsJNI.barra_qgMax_set(swigCPtr, this, value);
  }

  public double getQgMax() {
    return libepsJNI.barra_qgMax_get(swigCPtr, this);
  }

  public void setQgMin(double value) {
    libepsJNI.barra_qgMin_set(swigCPtr, this, value);
  }

  public double getQgMin() {
    return libepsJNI.barra_qgMin_get(swigCPtr, this);
  }

  public void setVMax(double value) {
    libepsJNI.barra_vMax_set(swigCPtr, this, value);
  }

  public double getVMax() {
    return libepsJNI.barra_vMax_get(swigCPtr, this);
  }

  public void setVMin(double value) {
    libepsJNI.barra_vMin_set(swigCPtr, this, value);
  }

  public double getVMin() {
    return libepsJNI.barra_vMin_get(swigCPtr, this);
  }

  public void setGsh(double value) {
    libepsJNI.barra_gsh_set(swigCPtr, this, value);
  }

  public double getGsh() {
    return libepsJNI.barra_gsh_get(swigCPtr, this);
  }

  public void setBsh(double value) {
    libepsJNI.barra_bsh_set(swigCPtr, this, value);
  }

  public double getBsh() {
    return libepsJNI.barra_bsh_get(swigCPtr, this);
  }

  public void setCtrlREM(double value) {
    libepsJNI.barra_ctrlREM_set(swigCPtr, this, value);
  }

  public double getCtrlREM() {
    return libepsJNI.barra_ctrlREM_get(swigCPtr, this);
  }

  public void setFlag(int value) {
    libepsJNI.barra_flag_set(swigCPtr, this, value);
  }

  public int getFlag() {
    return libepsJNI.barra_flag_get(swigCPtr, this);
  }

  public void setV0(double value) {
    libepsJNI.barra_v0_set(swigCPtr, this, value);
  }

  public double getV0() {
    return libepsJNI.barra_v0_get(swigCPtr, this);
  }

  public void setVEsp0(double value) {
    libepsJNI.barra_vEsp0_set(swigCPtr, this, value);
  }

  public double getVEsp0() {
    return libepsJNI.barra_vEsp0_get(swigCPtr, this);
  }

  public void setTheta0(double value) {
    libepsJNI.barra_theta0_set(swigCPtr, this, value);
  }

  public double getTheta0() {
    return libepsJNI.barra_theta0_get(swigCPtr, this);
  }

  public void setPg0(double value) {
    libepsJNI.barra_pg0_set(swigCPtr, this, value);
  }

  public double getPg0() {
    return libepsJNI.barra_pg0_get(swigCPtr, this);
  }

  public void setQg0(double value) {
    libepsJNI.barra_qg0_set(swigCPtr, this, value);
  }

  public double getQg0() {
    return libepsJNI.barra_qg0_get(swigCPtr, this);
  }

  public void setBsh0(double value) {
    libepsJNI.barra_bsh0_set(swigCPtr, this, value);
  }

  public double getBsh0() {
    return libepsJNI.barra_bsh0_get(swigCPtr, this);
  }

  public void setTipo0(int value) {
    libepsJNI.barra_tipo0_set(swigCPtr, this, value);
  }

  public int getTipo0() {
    return libepsJNI.barra_tipo0_get(swigCPtr, this);
  }

  public void setPs(double value) {
    libepsJNI.barra_ps_set(swigCPtr, this, value);
  }

  public double getPs() {
    return libepsJNI.barra_ps_get(swigCPtr, this);
  }

  public void setPd(double value) {
    libepsJNI.barra_pd_set(swigCPtr, this, value);
  }

  public double getPd() {
    return libepsJNI.barra_pd_get(swigCPtr, this);
  }

  public void setPs0(double value) {
    libepsJNI.barra_ps0_set(swigCPtr, this, value);
  }

  public double getPs0() {
    return libepsJNI.barra_ps0_get(swigCPtr, this);
  }

  public void setPd0(double value) {
    libepsJNI.barra_pd0_set(swigCPtr, this, value);
  }

  public double getPd0() {
    return libepsJNI.barra_pd0_get(swigCPtr, this);
  }

  public void setC_bid(double value) {
    libepsJNI.barra_c_bid_set(swigCPtr, this, value);
  }

  public double getC_bid() {
    return libepsJNI.barra_c_bid_get(swigCPtr, this);
  }

  public void setPsMax(double value) {
    libepsJNI.barra_psMax_set(swigCPtr, this, value);
  }

  public double getPsMax() {
    return libepsJNI.barra_psMax_get(swigCPtr, this);
  }

  public void setPsMin(double value) {
    libepsJNI.barra_psMin_set(swigCPtr, this, value);
  }

  public double getPsMin() {
    return libepsJNI.barra_psMin_get(swigCPtr, this);
  }

  public void setPdMax(double value) {
    libepsJNI.barra_pdMax_set(swigCPtr, this, value);
  }

  public double getPdMax() {
    return libepsJNI.barra_pdMax_get(swigCPtr, this);
  }

  public void setPdMin(double value) {
    libepsJNI.barra_pdMin_set(swigCPtr, this, value);
  }

  public double getPdMin() {
    return libepsJNI.barra_pdMin_get(swigCPtr, this);
  }

  public void setBshMax(double value) {
    libepsJNI.barra_bshMax_set(swigCPtr, this, value);
  }

  public double getBshMax() {
    return libepsJNI.barra_bshMax_get(swigCPtr, this);
  }

  public void setBshMin(double value) {
    libepsJNI.barra_bshMin_set(swigCPtr, this, value);
  }

  public double getBshMin() {
    return libepsJNI.barra_bshMin_get(swigCPtr, this);
  }

  public barra() {
    this(libepsJNI.new_barra(), true);
  }

}
