/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libeps;

public class eps {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected eps(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(eps obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libepsJNI.delete_eps(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBarras(barra value) {
    libepsJNI.eps_barras_set(swigCPtr, this, barra.getCPtr(value), value);
  }

  public barra getBarras() {
    long cPtr = libepsJNI.eps_barras_get(swigCPtr, this);
    return (cPtr == 0) ? null : new barra(cPtr, false);
  }

  public void setLigacoes(ligacao value) {
    libepsJNI.eps_ligacoes_set(swigCPtr, this, ligacao.getCPtr(value), value);
  }

  public ligacao getLigacoes() {
    long cPtr = libepsJNI.eps_ligacoes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ligacao(cPtr, false);
  }

  public void setBaseMVA(double value) {
    libepsJNI.eps_baseMVA_set(swigCPtr, this, value);
  }

  public double getBaseMVA() {
    return libepsJNI.eps_baseMVA_get(swigCPtr, this);
  }

  public void setBaseTensao(double value) {
    libepsJNI.eps_baseTensao_set(swigCPtr, this, value);
  }

  public double getBaseTensao() {
    return libepsJNI.eps_baseTensao_get(swigCPtr, this);
  }

  public void setNB(int value) {
    libepsJNI.eps_nB_set(swigCPtr, this, value);
  }

  public int getNB() {
    return libepsJNI.eps_nB_get(swigCPtr, this);
  }

  public void setRef(int value) {
    libepsJNI.eps_ref_set(swigCPtr, this, value);
  }

  public int getRef() {
    return libepsJNI.eps_ref_get(swigCPtr, this);
  }

  public void setNPQ(int value) {
    libepsJNI.eps_nPQ_set(swigCPtr, this, value);
  }

  public int getNPQ() {
    return libepsJNI.eps_nPQ_get(swigCPtr, this);
  }

  public void setNPV(int value) {
    libepsJNI.eps_nPV_set(swigCPtr, this, value);
  }

  public int getNPV() {
    return libepsJNI.eps_nPV_get(swigCPtr, this);
  }

  public eps() {
    this(libepsJNI.new_eps(), true);
  }

}
