/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libeps;

public class infoLigacao {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected infoLigacao(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(infoLigacao obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libepsJNI.delete_infoLigacao(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI(int value) {
    libepsJNI.infoLigacao_i_set(swigCPtr, this, value);
  }

  public int getI() {
    return libepsJNI.infoLigacao_i_get(swigCPtr, this);
  }

  public void setJ(int value) {
    libepsJNI.infoLigacao_j_set(swigCPtr, this, value);
  }

  public int getJ() {
    return libepsJNI.infoLigacao_j_get(swigCPtr, this);
  }

  public void setArea(int value) {
    libepsJNI.infoLigacao_area_set(swigCPtr, this, value);
  }

  public int getArea() {
    return libepsJNI.infoLigacao_area_get(swigCPtr, this);
  }

  public void setZonaPerdas(int value) {
    libepsJNI.infoLigacao_zonaPerdas_set(swigCPtr, this, value);
  }

  public int getZonaPerdas() {
    return libepsJNI.infoLigacao_zonaPerdas_get(swigCPtr, this);
  }

  public void setCircParalelos(int value) {
    libepsJNI.infoLigacao_circParalelos_set(swigCPtr, this, value);
  }

  public int getCircParalelos() {
    return libepsJNI.infoLigacao_circParalelos_get(swigCPtr, this);
  }

  public void setTipo(int value) {
    libepsJNI.infoLigacao_tipo_set(swigCPtr, this, value);
  }

  public int getTipo() {
    return libepsJNI.infoLigacao_tipo_get(swigCPtr, this);
  }

  public void setR(double value) {
    libepsJNI.infoLigacao_r_set(swigCPtr, this, value);
  }

  public double getR() {
    return libepsJNI.infoLigacao_r_get(swigCPtr, this);
  }

  public void setX(double value) {
    libepsJNI.infoLigacao_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return libepsJNI.infoLigacao_x_get(swigCPtr, this);
  }

  public void setBsh(double value) {
    libepsJNI.infoLigacao_bsh_set(swigCPtr, this, value);
  }

  public double getBsh() {
    return libepsJNI.infoLigacao_bsh_get(swigCPtr, this);
  }

  public void setLineRat1(int value) {
    libepsJNI.infoLigacao_lineRat1_set(swigCPtr, this, value);
  }

  public int getLineRat1() {
    return libepsJNI.infoLigacao_lineRat1_get(swigCPtr, this);
  }

  public void setLineRat2(int value) {
    libepsJNI.infoLigacao_lineRat2_set(swigCPtr, this, value);
  }

  public int getLineRat2() {
    return libepsJNI.infoLigacao_lineRat2_get(swigCPtr, this);
  }

  public void setLineRat3(int value) {
    libepsJNI.infoLigacao_lineRat3_set(swigCPtr, this, value);
  }

  public int getLineRat3() {
    return libepsJNI.infoLigacao_lineRat3_get(swigCPtr, this);
  }

  public void setTControl(int value) {
    libepsJNI.infoLigacao_tControl_set(swigCPtr, this, value);
  }

  public int getTControl() {
    return libepsJNI.infoLigacao_tControl_get(swigCPtr, this);
  }

  public void setSide(int value) {
    libepsJNI.infoLigacao_side_set(swigCPtr, this, value);
  }

  public int getSide() {
    return libepsJNI.infoLigacao_side_get(swigCPtr, this);
  }

  public void setTap(double value) {
    libepsJNI.infoLigacao_tap_set(swigCPtr, this, value);
  }

  public double getTap() {
    return libepsJNI.infoLigacao_tap_get(swigCPtr, this);
  }

  public void setPhi(double value) {
    libepsJNI.infoLigacao_phi_set(swigCPtr, this, value);
  }

  public double getPhi() {
    return libepsJNI.infoLigacao_phi_get(swigCPtr, this);
  }

  public void setTapMin(double value) {
    libepsJNI.infoLigacao_tapMin_set(swigCPtr, this, value);
  }

  public double getTapMin() {
    return libepsJNI.infoLigacao_tapMin_get(swigCPtr, this);
  }

  public void setTapMax(double value) {
    libepsJNI.infoLigacao_tapMax_set(swigCPtr, this, value);
  }

  public double getTapMax() {
    return libepsJNI.infoLigacao_tapMax_get(swigCPtr, this);
  }

  public void setPasso(double value) {
    libepsJNI.infoLigacao_passo_set(swigCPtr, this, value);
  }

  public double getPasso() {
    return libepsJNI.infoLigacao_passo_get(swigCPtr, this);
  }

  public void setCtrlMin(double value) {
    libepsJNI.infoLigacao_ctrlMin_set(swigCPtr, this, value);
  }

  public double getCtrlMin() {
    return libepsJNI.infoLigacao_ctrlMin_get(swigCPtr, this);
  }

  public void setCtrlMax(double value) {
    libepsJNI.infoLigacao_ctrlMax_set(swigCPtr, this, value);
  }

  public double getCtrlMax() {
    return libepsJNI.infoLigacao_ctrlMax_get(swigCPtr, this);
  }

  public void setG(double value) {
    libepsJNI.infoLigacao_g_set(swigCPtr, this, value);
  }

  public double getG() {
    return libepsJNI.infoLigacao_g_get(swigCPtr, this);
  }

  public void setB(double value) {
    libepsJNI.infoLigacao_b_set(swigCPtr, this, value);
  }

  public double getB() {
    return libepsJNI.infoLigacao_b_get(swigCPtr, this);
  }

  public void setPI(ligacao value) {
    libepsJNI.infoLigacao_pI_set(swigCPtr, this, ligacao.getCPtr(value), value);
  }

  public ligacao getPI() {
    long cPtr = libepsJNI.infoLigacao_pI_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ligacao(cPtr, false);
  }

  public void setPJ(ligacao value) {
    libepsJNI.infoLigacao_pJ_set(swigCPtr, this, ligacao.getCPtr(value), value);
  }

  public ligacao getPJ() {
    long cPtr = libepsJNI.infoLigacao_pJ_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ligacao(cPtr, false);
  }

  public void setTap0(double value) {
    libepsJNI.infoLigacao_tap0_set(swigCPtr, this, value);
  }

  public double getTap0() {
    return libepsJNI.infoLigacao_tap0_get(swigCPtr, this);
  }

  public void setIMax(double value) {
    libepsJNI.infoLigacao_iMax_set(swigCPtr, this, value);
  }

  public double getIMax() {
    return libepsJNI.infoLigacao_iMax_get(swigCPtr, this);
  }

  public infoLigacao() {
    this(libepsJNI.new_infoLigacao(), true);
  }

}
