/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libeps;

public interface libepsConstants {
  public final static double VMIN = libepsJNI.VMIN_get();
  public final static double VMAX = libepsJNI.VMAX_get();
  public final static double VMINPQ = libepsJNI.VMINPQ_get();
  public final static double VMAXPQ = libepsJNI.VMAXPQ_get();
  public final static int TAP = libepsJNI.TAP_get();
  public final static int IMPEDANCIA = libepsJNI.IMPEDANCIA_get();
  public final static String ARQ_3_BUS = libepsJNI.ARQ_3_BUS_get();
  public final static String ARQ_6_BUS = libepsJNI.ARQ_6_BUS_get();
  public final static String ARQ_STAGG_5 = libepsJNI.ARQ_STAGG_5_get();
  public final static String ARQ_CIGRE_32 = libepsJNI.ARQ_CIGRE_32_get();
  public final static String ARQ_IEEE_14_BUS = libepsJNI.ARQ_IEEE_14_BUS_get();
  public final static String ARQ_IEEE_30_BUS = libepsJNI.ARQ_IEEE_30_BUS_get();
  public final static String ARQ_IEEE_57_BUS = libepsJNI.ARQ_IEEE_57_BUS_get();
  public final static String ARQ_IEEE_118_BUS = libepsJNI.ARQ_IEEE_118_BUS_get();
  public final static String ARQ_IEEE_300_BUS = libepsJNI.ARQ_IEEE_300_BUS_get();
  public final static String ARQ_SUL_SUDESTE_BR = libepsJNI.ARQ_SUL_SUDESTE_BR_get();
}
