/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libeps;

public class ligacao {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ligacao(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ligacao obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libepsJNI.delete_ligacao(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInfo(infoLigacao value) {
    libepsJNI.ligacao_info_set(swigCPtr, this, infoLigacao.getCPtr(value), value);
  }

  public infoLigacao getInfo() {
    long cPtr = libepsJNI.ligacao_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new infoLigacao(cPtr, false);
  }

  public void setJ(int value) {
    libepsJNI.ligacao_j_set(swigCPtr, this, value);
  }

  public int getJ() {
    return libepsJNI.ligacao_j_get(swigCPtr, this);
  }

  public void setTBarra(int value) {
    libepsJNI.ligacao_tBarra_set(swigCPtr, this, value);
  }

  public int getTBarra() {
    return libepsJNI.ligacao_tBarra_get(swigCPtr, this);
  }

  public void setProx(ligacao value) {
    libepsJNI.ligacao_prox_set(swigCPtr, this, ligacao.getCPtr(value), value);
  }

  public ligacao getProx() {
    long cPtr = libepsJNI.ligacao_prox_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ligacao(cPtr, false);
  }

  public void setAnt(ligacao value) {
    libepsJNI.ligacao_ant_set(swigCPtr, this, ligacao.getCPtr(value), value);
  }

  public ligacao getAnt() {
    long cPtr = libepsJNI.ligacao_ant_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ligacao(cPtr, false);
  }

  public ligacao() {
    this(libepsJNI.new_ligacao(), true);
  }

}
