/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libeps;

public class param_fc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected param_fc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(param_fc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libepsJNI.delete_param_fc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTol(double value) {
    libepsJNI.param_fc_tol_set(swigCPtr, this, value);
  }

  public double getTol() {
    return libepsJNI.param_fc_tol_get(swigCPtr, this);
  }

  public void setMaximumNumberIterations(int value) {
    libepsJNI.param_fc_maximumNumberIterations_set(swigCPtr, this, value);
  }

  public int getMaximumNumberIterations() {
    return libepsJNI.param_fc_maximumNumberIterations_get(swigCPtr, this);
  }

  public void setFlatstart(int value) {
    libepsJNI.param_fc_flatstart_set(swigCPtr, this, value);
  }

  public int getFlatstart() {
    return libepsJNI.param_fc_flatstart_get(swigCPtr, this);
  }

  public void setVoltageControlPVBusType(int value) {
    libepsJNI.param_fc_voltageControlPVBusType_set(swigCPtr, this, value);
  }

  public int getVoltageControlPVBusType() {
    return libepsJNI.param_fc_voltageControlPVBusType_get(swigCPtr, this);
  }

  public void setVoltageLimitsPQBusType(int value) {
    libepsJNI.param_fc_voltageLimitsPQBusType_set(swigCPtr, this, value);
  }

  public int getVoltageLimitsPQBusType() {
    return libepsJNI.param_fc_voltageLimitsPQBusType_get(swigCPtr, this);
  }

  public void setAlternateBetweenNRIterations(int value) {
    libepsJNI.param_fc_alternateBetweenNRIterations_set(swigCPtr, this, value);
  }

  public int getAlternateBetweenNRIterations() {
    return libepsJNI.param_fc_alternateBetweenNRIterations_get(swigCPtr, this);
  }

  public void setPrintDetails(int value) {
    libepsJNI.param_fc_printDetails_set(swigCPtr, this, value);
  }

  public int getPrintDetails() {
    return libepsJNI.param_fc_printDetails_get(swigCPtr, this);
  }

  public void setGenerate_new_system(int value) {
    libepsJNI.param_fc_generate_new_system_set(swigCPtr, this, value);
  }

  public int getGenerate_new_system() {
    return libepsJNI.param_fc_generate_new_system_get(swigCPtr, this);
  }

  public param_fc() {
    this(libepsJNI.new_param_fc(), true);
  }

}
